### ISSUE TITLE
[ BUG ] analysis函数两种报错

### ISSUE THREAD

**Issue by tdifg** [LoRexxar/Cobra-W#1]
```
[WARNING] [MainThread] [10:26:52] [engine.py:582] Traceback (most recent call last):
  File "/Users/litiezhu/Cobra-W/cobra/engine.py", line 560, in scan
    result = scan_parser(code_contents, rule_match, self.line_number, self.file_path)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 778, in scan_parser
    analysis(all_nodes, func, back_node, int(vul_lineno), file_path, function_params=None)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 756, in analysis
    analysis(node.nodes, vul_function, back_node, vul_lineo, function_params)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 753, in analysis
    analysis(node.nodes, vul_function, function_body, vul_lineo, function_params=function_params, file_path=file_path)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 744, in analysis
    analysis_if_else(node, back_node, vul_function, vul_lineo, function_params, file_path=file_path)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 564, in analysis_if_else
    analysis(node.else_.node.nodes, vul_function, back_node, vul_lineno, function_params, file_path=file_path)
TypeError: analysis() got multiple values for keyword argument 'file_path'

```

主要是analysis函数的`file_path`参数位置错误，修改完后还有`TypeError: analysis() takes at least 5 arguments (4 given)`的错误，详情：

```
[WARNING] [MainThread] [10:28:06] [engine.py:582] Traceback (most recent call last):
  File "/Users/litiezhu/Cobra-W/cobra/engine.py", line 560, in scan
    result = scan_parser(code_contents, rule_match, self.line_number, self.file_path)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 778, in scan_parser
    analysis(all_nodes, func, back_node, int(vul_lineno), file_path, function_params=None)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 756, in analysis
    analysis(node.nodes, vul_function, back_node, vul_lineo, function_params)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 753, in analysis
    analysis(node.nodes, vul_function, function_body, vul_lineo, function_params=function_params, file_path=file_path)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 728, in analysis
    analysis(buffer_, vul_function, back_node, vul_lineo, function_params)
  File "/Users/litiezhu/Cobra-W/cobra/parser.py", line 735, in analysis
    analysis(nodes, vul_function, back_node, vul_lineo)
TypeError: analysis() takes at least 5 arguments (4 given)
```

**Comment by LoRexxar** [comment]
我看看

**Comment by LoRexxar** [comment]
你clone一下develop分支，应该修复了
